version: '3.4'

services:
 samba:
   container_name: samba
   image: dperson/samba
   environment:
     TZ: '${TZ-Europe/London}'
   networks:
     - default
   ports:
     - "137:137/udp"
     - "138:138/udp"
     - "139:139/tcp"
     - "445:445/tcp"
   read_only: true
   tmpfs:
     - /tmp
   restart: unless-stopped
   stdin_open: true
   tty: true
   volumes:
     - ${BACKUP_VOLUME:-/media/tm}:/backup:z
   command: '-p -s "TimeMachine Home;/backup/%U;yes;no;no;%U;;%U" {USERS}'
