version: '3.4'

services:
 avahi:
   container_name: avahi
   image: solidnerd/avahi:0.7
   network_mode: host
   volumes:
     - ./avahi:/etc/avahi:ro
   restart: unless-stopped
 samba:
   container_name: samba
   image: dperson/samba
   environment:
     TZ: '${TZ-Europe/London}'
   networks:
     - default
   ports:
     - "137:137/udp"
     - "138:138/udp"
     - "139:139/tcp"
     - "445:445/tcp"
   read_only: true
   tmpfs:
     - /tmp
   restart: unless-stopped
   stdin_open: true
   tty: true
   volumes:
     - ${BACKUP_VOLUME:-~/tmbackup/data}:/backup:z
   command: '-s "Time Machine Backup;/backup;yes;no" -u "${SAMBA_USER:-tm_user};${SAMBA_PASS:-tm_pw}"'
